### ISSUE TITLE
Is there any API doc for moving file from folder to folder?

### ISSUE THREAD

**Issue by ghost** [pCloud/pcloud-sdk-js#52]
Hello pCloud Dev team, please correct me if I'm wrong but is there any API doc for moving file from folder to another folder?

**Comment by gsyarov** [comment]
Hello @eontrix, check this method https://docs.pcloud.com/methods/file/renamefile.html

**Comment by ghost** [comment]
> https://docs.pcloud.com/methods/file/renamefile.html

Hi @gsyarov thank you so much for your help, I already try it with just 2 param key path and topath and it worked....
thank you mate :)
